version: "3.7"

services:
  nudges:
    build: .
    command: uvicorn wsgi:app  --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cardGameDB
    expose:
      - 5432
    ports:
      - 5432:5432

volumes:
  postgres_data:
