name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t card-matching-game .
      - name: Build, Push and Deploy to Heroku
        id: Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: wallravit@gmail.com
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: cards-matching-game
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
